<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-Q955AKM" failures="1" tests="1" name="Test" time="6.263" errors="0" timestamp="2021-10-13T11:47:28 PDT">
  <testcase classname="IKApi.StarWars.test.TC001_GetPeople" name="getAllPeople" time="4.553">
    <failure type="java.lang.IllegalAccessError" message="class IKApi.StarWars.test.TC001_GetPeople (in unnamed module @0xc2e1f26) cannot access class jdk.internal.org.jline.utils.Log (in module jdk.internal.le) because module jdk.internal.le does not export jdk.internal.org.jline.utils to unnamed module @0xc2e1f26">
      <![CDATA[java.lang.IllegalAccessError: class IKApi.StarWars.test.TC001_GetPeople (in unnamed module @0xc2e1f26) cannot access class jdk.internal.org.jline.utils.Log (in module jdk.internal.le) because module jdk.internal.le does not export jdk.internal.org.jline.utils to unnamed module @0xc2e1f26
at IKApi.StarWars.test.TC001_GetPeople.getAllPeople(TC001_GetPeople.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- getAllPeople -->
</testsuite> <!-- Test -->
